### ISSUE TITLE
Don't self host presenter logos

### ISSUE THREAD

**Issue by farooqkz** [pcworms/meetings-banner#2]
People usually have got an account some where, such as Github, Gitlab or elsewhere. I suggest using these hosted images instead of uploading these images to the Github repo. It'll have several advantages, one of them being not using Git for binary files which could possibly create headache. Second, we only change a URL each time and voila. cc @bsimjoo @ahangarha @simon-laux

**Comment by farooqkz** [comment]
Hi Simon! I am asking for your comment in this if you can provide us some insight :)

This is a meeting page, each Friday we have a meeting and we show the presenter, the subject to get presented and the presenter's avatar. I am proposing we use a URL for the avatar/image rather than uploading the file each time to git.

**Comment by Simon-Laux** [comment]
> Git for binary files which could possibly create headache

I think for images it makes no big difference yet, it's more about large files like big 3d models in game development or big training data for ai, generally multiple gigabytes where it becomes annoying to use git for large binary files. This is generally the time when things like https://git-lfs.com come into play.

I think for avatars and screenshots it's fine to store them in a git repo:
- relying on an external CDN, like GitHub, discord media or stuff like that can be unreliable, because media can be deleted and changed which would potentially break your site
- Losing the images from the same domain/origin can be beneficial, because the server could make use of http3 to fetch all needed images in one request, this is not possible if the content is stored on multiple different servers, also there are no potential problems with stuff like CORS if everything comes from the same host


Also I would not really upload duplicated files to git, maybe make an presenter folder, and reuse the avatar from there when the same presenter has a second talk.

just my 2cents because you asked for my opinion.

**Comment by farooqkz** [comment]
@Simon-Laux Thank you so much for the 2 cents :)

Waiting for Behnam and Mustafa for their opinions.
